let promptList = ["Aurora Borealis",
    "Avalanche",
    "Befana",
    "Candy Cane",
    "Can’t Get Warm",
    "Christmas Lights",
    "Christmas Tree",
    "Christmas Song",
    "Church",
    "Cozy Cabin",
    "Creatures Under The Frozen Lake",
    "Cryptids In Winter",
    "Cutting Down the Tree",
    "Deck the Halls",
    "Ded Moroz and Snegurochka",
    "Eggnog",
    "Elves Infestation",
    "Evergreen Forest",
    "Figures In The Snow Storm",
    "First Snow of Winter",
    "Footprints in the Snow",
    "Frau Perchta",
    "Frost Webs ",
    "Frostbite",
    "Frosty the Snowman",
    "Fruitcake",
    "Furs",
    "Ghost of Christmas Past, Present and Future",
    "Gifts",
    "Gingerbread House",
    "Grinch",
    "Gryla & the Yule Lads",
    "Hans Trapp",
    "He see you when you sleeping",
    "Husky",
    "Ice Skating Rink",
    "Icicles",
    "I found the body inside the snowman",
    "It's cold outside. Let them in",
    "Jack Frost",
    "Jingle Bells",
    "Krampus",
    "Mall Santa",
    "Man Eating Wreath",
    "Mistletoe",
    "Monsters Go Caroling",
    "Mountain Giants",
    "Mouse King",
    "Nostalgia",
    "Nutcracker",
    "Polar Bear",
    "Polar Express",
    "Red Nose",
    "Reindeer",
    "Saint Nick",
    "Santa’s Claws",
    "Skiing",
    "Snow Angel",
    "Snow Fort",
    "Snow Globe",
    "Snowball Fight",
    "Snowfall",
    "Sugar Plums",
    "Star of Bethlehem",
    "Stockings Hung by the Chimney",
    "Winter Moon",
    "Winter Night",
    "Up On The Roof Top",
    "Yeti",
    "Yuki-onna",
    "Yule Cat",
    "Yule Goat"
]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n]
}
