let promptList = ["Aurora Borealis",
    "Avalanche",
    "Befana",
    "Belsnickel",
    "Candy Cane",
    "Can’t Get Warm",
    "Cave Mouth",
    "Christmas Lights",
    "Christmas List",
    "Christmas Tree",
    "Christmas Song",
    "Church",
    "Cozy Cabin",
    "Creatures Under The Frozen Lake",
    "Cryptids In Winter",
    "Cutting Down the Tree",
    "Deck the Halls",
    "Ded Moroz and Snegurochka",
    "Dwarf Infestation",
    "Eggnog",
    "Elves Infestation",
    "Evergreen Forest",
    "Figures In The Snow Storm",
    "First Snow of Winter",
    "Footprints in the Snow",
    "Frau Perchta",
    "Frost Webs ",
    "Frostbite",
    "Frosty the Snowman",
    "Fruitcake",
    "Furs",
    "Ghost of Christmas Past, Present and Future",
    "Gifts",
    "Gingerbread House",
    "Golem",
    "Grinch",
    "Gryla",
    "Hans Trapp",
    "Hanukkah",
    "He see you when you sleeping",
    "Hot Chocolate",
    "Husky",
    "Ice Skating Rink",
    "Icicles",
    "I found the body inside the snowman",
    "It's cold outside. Let them in",
    "Jack Frost",
    "Jingle Bells",
    "Krampus",
    "Little Matchstick Girl",
    "Mall Santa",
    "Man Eating Wreath",
    "Misfit Toys",
    "Mistletoe",
    "Monsters Go Caroling",
    "Mountain Climber",
    "Mountain Giants",
    "Mouse King",
    "Narwal",
    "Nostalgia",
    "Nutcracker",
    "Open Window",
    "Penguin",
    "Polar Bear",
    "Polar Express",
    "Puffin",
    "Red Nose",
    "Reindeer",
    "Saint Nick",
    "Santa’s Claws",
    "Schnabelperchten",
    "Skiing",
    "Snow Angel",
    "Snow Fort",
    "Snow Globe",
    "Snow Queen",
    "Snowball Fight",
    "Snowfall",
    "Sugar Plums",
    "Star of Bethlehem",
    "Stockings Hung by the Chimney",
    "Three Kings",
    "Ugly Sweater",
    "Up On The Roof Top",
    "Wild Hunt",
    "Winter Moon",
    "Winter Night",
    "Winter Werewolf",
    "Yeti",
    "Yuki-onna",
    "Yule Cat",
    "Yule Goat",
    "Yule Lads",
    "Yule Log",
]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n]
}
